version: "2.1"

volumes:
  plex:

services:
  # https://hub.docker.com/r/linuxserver/plex
  plex:
    build:
      context: .
      dockerfile: Dockerfile.plex
    privileged: true
    network_mode: host
    volumes:
      - plex:/config
    environment:
      PUID: "1000"
      PGID: "1000"
