version: "2.1"

volumes:
  plex:
  duplicati:

services:
  # https://hub.docker.com/r/linuxserver/plex
  plex:
    build:
      context: .
      dockerfile: Dockerfile.plex
    privileged: true
    network_mode: host
    volumes:
      - plex:/config
    environment:
      PUID: "1000"
      PGID: "1000"

  # https://hub.docker.com/r/linuxserver/duplicati
  duplicati:
    image: linuxserver/duplicati
    environment:
      PUID: "0"
      PGID: "0"
      CLI_ARGS: --webservice-interface=any
    ports:
      - 8200:8200/tcp
    volumes:
      - duplicati:/config
      - plex:/source/plex:ro
